version: "1.0.0"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baedalsodae-app
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"
    environment:
      API_SERVER_PORT: ${API_SERVER_PORT}
      ENCRYPTION_AES_KEY: ${ENCRYPTION_AES_KEY}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DB_URL: ${POSTGRES_DB_URL}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DEFAULT_SCHEMA: ${POSTGRES_DEFAULT_SCHEMA}
      REDIS_URL: ${REDIS_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs  # Optional: for persistent logs
    depends_on:
       postgres:
         condition: service_healthy
       redis:
         condition: service_healthy

  mock-pg:
    build:
      context: ./mock-pg
      dockerfile: Dockerfile
    container_name: baedalsodae-mock-pg
    ports:
      - "8089:8080"