spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_schema: baedalsodae
        format_sql: true
        jdbc.time_zone: Asia/Seoul
  sql:
    init:
      mode: never

encryption:
  aes:
    key: ${ENCRYPTION_AES_KEY}