spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_schema: baedalsodae
        format_sql: true
        jdbc.time_zone: Asia/Seoul
  sql:
    init:
      mode: never

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        initialize-schema: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

server:
  port: 18082

logging:
  level:
    org.springframework.boot.diagnostics: DEBUG
    org.springframework.boot.web.embedded.tomcat: DEBUG
    org.apache.catalina: DEBUG

encryption:
  aes:
    key: ${ENCRYPTION_AES_KEY}

pg:
  url: http://localhost:8089