spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: false
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul
  sql:
    init:
      mode: never
  data:
    redis:
      host: localhost
      port: 6379
  ai:
    openai:
      api-key: dummy-key-for-test

JWT_SECRET: dGVzdFNlY3JldEtleUZvclRlc3RpbmdQdXJwb3Nlc09ubHk= #testSecretKeyForTestingPurposesOnly
JWT_EXPIRATION: 100000

encryption:
  aes:
    key: test-aes-key-16b

pg:
  url: http://localhost:8089

logging:
  level:
    org.springframework.boot.diagnostics: DEBUG
    org.springframework.boot.web.embedded.tomcat: DEBUG
    org.apache.catalina: DEBUG
