name: "✨ Issue Template ✨"
description: "이슈 템플릿"
body:
  - type: textarea
    id: content
    attributes:
      label: "✅ 내용"
      description: "할 일을 체크박스 형태로 작성해주세요."
      value: |
        ## 📌 작업 설명
        - 
        -
        
        ## 🔍 작업 목적
        - 
        -
        
        ## ✅ 세부 작업 항목
        - [x] 
        - [] 
        - []
        
        ## 🔗 관련 이슈
        연관된 이슈 번호가 있다면 작성하세요. (ex. #12)
    validations:
      required: true
