package com.project.baedalsodae.event.entity;

public enum EventType {
    ORDER_CREATED,
    ORDER_UPDATED,
    ORDER_DELETED,
    ORDER_CANCEL_REQUESTED,
    ORDER_DELIVERED,
    PAYMENT_CREATED,
    PAYMENT_UPDATED,
    PAYMENT_CANCEL_REQUESTED, PAYMENT_DELETED
}
